# Site Settings
title: Aquacise
email: aquaciseswimming@gmail.com
description: >
  Aquacise Lessons !
baseurl: ""
url: "http://originaldogmeat.github.io/aquacise"
twitter_username: 
github_username:  originaldogmeat
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM