# Site Settings
title: Aquacise
email: aquaciseswimming@gmail.com
description: >
  Aquacise Lessons !
baseurl: "/aquacise"
url: "http://originaldogmeat.github.io"
twitter_username: 
github_username:  originaldogmeat
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM