# Site Settings
title: Aquacise
email: aquaciseswimming@gmail.com
description: >
  Aquacise Lessons !
baseurl: ""
<<<<<<< HEAD
url: "http://originaldogmeat.github.io/aquacise"
=======
url: "https://originaldogmeat.github.io/Aquacise"
>>>>>>> origin/master
twitter_username: 
github_username:  originaldogmeat
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
