# Site Settings
title: Aquacise
email: aquaciseswimming@gmail.com
description: >
  Aquacise Swimming Lessons
baseurl: ""
url: "https://originaldogmeat.github.io/Aquacise/"
twitter_username: 
github_username:  originaldogmeat
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
